export const PATH_SEGMENTS = {
  SECURE: 'secure',
  AUTH: 'auth',
  DASHBOARD: 'dashboard',
  PROJECT_DETAILS: 'project-details',
  NOTE: 'note',
};

export const AUTH_PATH_SEGMENTS = {
  LOGIN: 'login',
};

export const NOTE_PATH_SEGMENTS = {
  NOTE_DETAILS: 'note-details',
  CREATE_NOTE: 'create-note',
};

export const PATH_DASHBOARD = `${PATH_SEGMENTS.SECURE}/${PATH_SEGMENTS.DASHBOARD}`;
export const PATH_PROJECT_DETAILS = `${PATH_SEGMENTS.SECURE}/${PATH_SEGMENTS.PROJECT_DETAILS}`;

export const PATH_NOTE = `${PATH_SEGMENTS.SECURE}/${PATH_SEGMENTS.NOTE}`;
export const PATH_NOTE_DETAILS = `${PATH_SEGMENTS.SECURE}/${PATH_SEGMENTS.NOTE}/${NOTE_PATH_SEGMENTS.NOTE_DETAILS}`;
export const PATH_NOTE_CREATE = `${PATH_SEGMENTS.SECURE}/${PATH_SEGMENTS.NOTE}/${NOTE_PATH_SEGMENTS.CREATE_NOTE}`;

export const PATH_LOGIN = `${PATH_SEGMENTS.AUTH}/${AUTH_PATH_SEGMENTS.LOGIN}`;
